name: Publish Python Package to PyPi
on:
  release:
    types: [published]

permissions: {}

jobs:
  publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: pdm-project/setup-pdm@973541a5febeafcfdadf8a51211435be6ecfd90f # v4.5

      - name: Publish package distributions to PyPI
        run: pdm publish
